### ISSUE TITLE
adapt issues

### ISSUE THREAD

**Issue by oliverfoster** [FrankBohac/adapt#1]
Do you have Skype? It'd be nice to talk to you about Adapt and see if I can help you get up to speed with the tools. 

My email address and Skype name is oliver.foster@kineo.com

**Comment by FrankBohac** [comment]
Yes, I have Skype. We would need to schedule a time when we are both available (I’m in Tucson Arizona so the time zones may be a problem).

**Comment by oliverfoster** [comment]
I can talk in my evenings. Which'll be your mid-morning. If you add me to Skype we can figure it out there. It's late for you now and early for me, so we can talk later if you like?

**Comment by oliverfoster** [comment]
I'm in Brighton, England.

**Comment by FrankBohac** [comment]
Its about 12:30 am here right now. Im up because I have to prep for a procedure at hospital tomorrow. Lets try and hook up next week after I get back home if that’s OK for you.

**Comment by oliverfoster** [comment]
Sounds good. Hope the hospital stuff goes well.

**Comment by FrankBohac** [comment]
Thanks.

I’ll re-contact you after the weekend.

**Comment by FrankBohac** [comment]
Hi,

Im ready to give it a try. Can we connect on Skype and hopefully you can get me past the installation problems I am having.

What day/time will work?

Frank

**Comment by oliverfoster** [comment]
Hi Frank,

Sorry, I completely forgot about this message. Too busy at the moment.

How is tomorrow, 2nd/09/2015, at 5pm my time, 9am your time?

**Comment by FrankBohac** [comment]
HI,

I am going to be checked into a hospital tomorrow. I’ll be there for about a month. I understand that for the first part I will be in pretty bad shape, but after about two weeks, I should be able to work with you. I’ll contact you back when I know more.

Frank

**Comment by FrankBohac** [comment]
Hi,

Im ready to go. I haven’t heard back from anyone regarding this issue for over a month…

Frank
